name:  1- push auf Dockerhub und deployment auf OpenShift

on:
  workflow_dispatch:

env:
  IMAGE_NAME: kunde
  IMAGE_VERSION: latest
  REGISTRY: docker.io/juergenzimmermann
  #PULL_SECRET_NAME: azr-secret
  OPENSHIFT_SERVER: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
  OPENSHIFT_NAMESPACE: juergen-zimmermann-dev

jobs:
    build-push-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v3
      
        - name: 'Java Einrichten, um ./gradlew bootBuildImage auszuführen'
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: 20
          
        #Berechtigung wird benötigt, damit der Runner "./gradlew <Task>" ausführen kann
        - name: './gradlew Berechtigungen anpassen'
          run: chmod +x ./gradlew
        
        - name: 'Login, Build und pushen vom image'
          uses: docker/login-action@v2
          with:
            username: juergenzimmermann
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - run: |
              ./gradlew bootBuildImage
              docker tag juergenzimmermann/kunde:2023.1.0 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
              docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
      
        - name: 'Einloggen in OpenShift'
          uses: redhat-actions/oc-login@v1
          with:
            openshift_server_url: ${{ env.OPENSHIFT_SERVER }} 
            openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
            insecure_skip_tls_verify: true
            namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      
        - name: 'OC auf dem Runner installieren'
          uses: redhat-actions/oc-installer@v1
          with:
            oc_version: '4.6'
      
        - name: 'Deployment der Kundenanwendung auf OpenShift'
          run: |
              oc apply -f deployment.yaml
              oc apply -f service.yaml
              oc apply -f route.yaml
